spring:
  application:
    name: eureka-discovery-client-app
server:
  port: 8089
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
     preferIpAddress: true